"""add user_code to users/

Revision ID: 65ad5d6b5b7e
Revises: ebfc8f473775
Create Date: 2026-05-13 14:35:47.733591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65ad5d6b5b7e'
down_revision: Union[str, Sequence[str], None] = 'ebfc8f473775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_user_code'), 'users', ['user_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_code'), table_name='users')
    op.drop_column('users', 'user_code')
    # ### end Alembic commands ###
