"""resolved the relationship mapper ambiguity and cycle

Revision ID: c68d87c369c0
Revises: af214072dfaa
Create Date: 2026-07-09 23:25:37.687412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c68d87c369c0'
down_revision: Union[str, Sequence[str], None] = 'af214072dfaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_ghost', sa.Boolean(), nullable=False, server_default=sa.text("false"),),)
    op.alter_column('users', 'is_ghost', server_default=None)
    op.add_column('users', sa.Column('ghost_owner_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('shadow_group_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_ghost_owner_id'), 'users', ['ghost_owner_id'], unique=False)
    op.create_foreign_key('fk_users_shadow_group_id_groups', 'users', 'groups', ['shadow_group_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'users', 'users', ['ghost_owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint('fk_users_shadow_group_id_groups', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_ghost_owner_id'), table_name='users')
    op.drop_column('users', 'shadow_group_id')
    op.drop_column('users', 'ghost_owner_id')
    op.drop_column('users', 'is_ghost')
    # ### end Alembic commands ###
