"""make user_code non-nulable in  users

Revision ID: f0847bad265b
Revises: 65ad5d6b5b7e
Create Date: 2026-05-13 14:41:06.970656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0847bad265b'
down_revision: Union[str, Sequence[str], None] = '65ad5d6b5b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
